name: "Push main workflow"

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.x
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: npm run buildPages && cp -r base code web-app

      - uses: actions/upload-pages-artifact@v1
        with:
          path: web-app/

  deploy-pages:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    permissions:
      contents: "read"
      id-token: "write"
      pages: "write"

    steps:
      - uses: actions/configure-pages@v1
      - id: deployment
        uses: actions/deploy-pages@main
